//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableUser", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class SerializableUser : object
    {
        
        private string[] AllergiesField;
        
        private string EmailField;
        
        private int IdField;
        
        private bool IsConfirmedField;
        
        private AccountService.SerializableKitchen[] KitchensField;
        
        private bool VeganField;
        
        private bool VegetarianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Allergies
        {
            get
            {
                return this.AllergiesField;
            }
            set
            {
                this.AllergiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmed
        {
            get
            {
                return this.IsConfirmedField;
            }
            set
            {
                this.IsConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.SerializableKitchen[] Kitchens
        {
            get
            {
                return this.KitchensField;
            }
            set
            {
                this.KitchensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vegan
        {
            get
            {
                return this.VeganField;
            }
            set
            {
                this.VeganField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vegetarian
        {
            get
            {
                return this.VegetarianField;
            }
            set
            {
                this.VegetarianField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableKitchen", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class SerializableKitchen : object
    {
        
        private int IdField;
        
        private AccountService.SerializableFood[] InventoryField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.SerializableFood[] Inventory
        {
            get
            {
                return this.InventoryField;
            }
            set
            {
                this.InventoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableFood", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class SerializableFood : object
    {
        
        private System.Nullable<System.DateTime> ExpiryDateField;
        
        private bool FavouriteField;
        
        private int IdField;
        
        private string[] IngredientsField;
        
        private string NameField;
        
        private bool OnShoppingListField;
        
        private double QuantityField;
        
        private string QuantityClassifierField;
        
        private string StorageField;
        
        private string[] TracesField;
        
        private int VeganField;
        
        private int VegetarianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Favourite
        {
            get
            {
                return this.FavouriteField;
            }
            set
            {
                this.FavouriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Ingredients
        {
            get
            {
                return this.IngredientsField;
            }
            set
            {
                this.IngredientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnShoppingList
        {
            get
            {
                return this.OnShoppingListField;
            }
            set
            {
                this.OnShoppingListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityClassifier
        {
            get
            {
                return this.QuantityClassifierField;
            }
            set
            {
                this.QuantityClassifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Storage
        {
            get
            {
                return this.StorageField;
            }
            set
            {
                this.StorageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Traces
        {
            get
            {
                return this.TracesField;
            }
            set
            {
                this.TracesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vegan
        {
            get
            {
                return this.VeganField;
            }
            set
            {
                this.VeganField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vegetarian
        {
            get
            {
                return this.VegetarianField;
            }
            set
            {
                this.VegetarianField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Storage", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public enum Storage : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fridge = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Freezer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pantry = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cupboard = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cellar = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableFoodFactsProductModel", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Models")]
    public partial class SerializableFoodFactsProductModel : object
    {
        
        private string Image_UrlField;
        
        private string[] IngredientsField;
        
        private string NameField;
        
        private System.Collections.Generic.Dictionary<string, string> NutrientsField;
        
        private int ServingQuantityField;
        
        private string ServingSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Url
        {
            get
            {
                return this.Image_UrlField;
            }
            set
            {
                this.Image_UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Ingredients
        {
            get
            {
                return this.IngredientsField;
            }
            set
            {
                this.IngredientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Nutrients
        {
            get
            {
                return this.NutrientsField;
            }
            set
            {
                this.NutrientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServingQuantity
        {
            get
            {
                return this.ServingQuantityField;
            }
            set
            {
                this.ServingQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServingSize
        {
            get
            {
                return this.ServingSizeField;
            }
            set
            {
                this.ServingSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class User : object
    {
        
        private string AllergiesField;
        
        private bool CalorieTrackerField;
        
        private AccountService.CaloriesInDay[] CaloriesInDaysField;
        
        private string EmailField;
        
        private System.Guid EmailConfirmKeyField;
        
        private int IdField;
        
        private bool IsConfirmedField;
        
        private AccountService.Kitchen[] KitchensField;
        
        private string PasswordField;
        
        private bool VeganField;
        
        private bool VegetarianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Allergies
        {
            get
            {
                return this.AllergiesField;
            }
            set
            {
                this.AllergiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CalorieTracker
        {
            get
            {
                return this.CalorieTrackerField;
            }
            set
            {
                this.CalorieTrackerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.CaloriesInDay[] CaloriesInDays
        {
            get
            {
                return this.CaloriesInDaysField;
            }
            set
            {
                this.CaloriesInDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EmailConfirmKey
        {
            get
            {
                return this.EmailConfirmKeyField;
            }
            set
            {
                this.EmailConfirmKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmed
        {
            get
            {
                return this.IsConfirmedField;
            }
            set
            {
                this.IsConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.Kitchen[] Kitchens
        {
            get
            {
                return this.KitchensField;
            }
            set
            {
                this.KitchensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vegan
        {
            get
            {
                return this.VeganField;
            }
            set
            {
                this.VeganField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vegetarian
        {
            get
            {
                return this.VegetarianField;
            }
            set
            {
                this.VegetarianField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaloriesInDay", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class CaloriesInDay : object
    {
        
        private int CaloriesField;
        
        private System.DateTime DayField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Calories
        {
            get
            {
                return this.CaloriesField;
            }
            set
            {
                this.CaloriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Day
        {
            get
            {
                return this.DayField;
            }
            set
            {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kitchen", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class Kitchen : object
    {
        
        private int IdField;
        
        private AccountService.Food[] InventoryField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.Food[] Inventory
        {
            get
            {
                return this.InventoryField;
            }
            set
            {
                this.InventoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Food", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Classes")]
    public partial class Food : object
    {
        
        private System.Nullable<System.DateTime> CalculatedExpiryDateField;
        
        private int CaloriesField;
        
        private System.Nullable<System.DateTime> ExpiryDateField;
        
        private bool FavouriteField;
        
        private int IdField;
        
        private string IngredientsField;
        
        private double InitialQuantityField;
        
        private string InitialQuantityClassifierField;
        
        private string NameField;
        
        private bool OnShoppingListField;
        
        private double QuantityField;
        
        private string QuantityClassifierField;
        
        private AccountService.Storage StorageField;
        
        private string TracesField;
        
        private int VeganField;
        
        private int VegetarianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CalculatedExpiryDate
        {
            get
            {
                return this.CalculatedExpiryDateField;
            }
            set
            {
                this.CalculatedExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Calories
        {
            get
            {
                return this.CaloriesField;
            }
            set
            {
                this.CaloriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Favourite
        {
            get
            {
                return this.FavouriteField;
            }
            set
            {
                this.FavouriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ingredients
        {
            get
            {
                return this.IngredientsField;
            }
            set
            {
                this.IngredientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialQuantity
        {
            get
            {
                return this.InitialQuantityField;
            }
            set
            {
                this.InitialQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialQuantityClassifier
        {
            get
            {
                return this.InitialQuantityClassifierField;
            }
            set
            {
                this.InitialQuantityClassifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnShoppingList
        {
            get
            {
                return this.OnShoppingListField;
            }
            set
            {
                this.OnShoppingListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityClassifier
        {
            get
            {
                return this.QuantityClassifierField;
            }
            set
            {
                this.QuantityClassifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.Storage Storage
        {
            get
            {
                return this.StorageField;
            }
            set
            {
                this.StorageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Traces
        {
            get
            {
                return this.TracesField;
            }
            set
            {
                this.TracesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vegan
        {
            get
            {
                return this.VeganField;
            }
            set
            {
                this.VeganField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vegetarian
        {
            get
            {
                return this.VegetarianField;
            }
            set
            {
                this.VegetarianField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableRecipeModel", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Models")]
    public partial class SerializableRecipeModel : object
    {
        
        private AccountService.EdamanIngredientScored[] EdamanIngredientsField;
        
        private string[] HealthLabelsField;
        
        private string ImageField;
        
        private AccountService.IngredientModel[] IngredientsField;
        
        private string NameField;
        
        private int ScoreField;
        
        private string SourceField;
        
        private string UrlField;
        
        private double YieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.EdamanIngredientScored[] EdamanIngredients
        {
            get
            {
                return this.EdamanIngredientsField;
            }
            set
            {
                this.EdamanIngredientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] HealthLabels
        {
            get
            {
                return this.HealthLabelsField;
            }
            set
            {
                this.HealthLabelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.IngredientModel[] Ingredients
        {
            get
            {
                return this.IngredientsField;
            }
            set
            {
                this.IngredientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Yield
        {
            get
            {
                return this.YieldField;
            }
            set
            {
                this.YieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EdamanIngredientScored", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Models")]
    public partial class EdamanIngredientScored : object
    {
        
        private string NameField;
        
        private int ScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IngredientModel", Namespace="http://schemas.datacontract.org/2004/07/Capstone.Models")]
    public partial class IngredientModel : object
    {
        
        private string NameField;
        
        private string OriginalNameField;
        
        private int ScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalName
        {
            get
            {
                return this.OriginalNameField;
            }
            set
            {
                this.OriginalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountServiceMvc")]
    public interface IAccountServiceMvc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/CreateAccount", ReplyAction="http://tempuri.org/IAccountServiceMvc/CreateAccountResponse")]
        AccountService.SerializableUser CreateAccount(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/CreateAccount", ReplyAction="http://tempuri.org/IAccountServiceMvc/CreateAccountResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableUser> CreateAccountAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/LoginAccount", ReplyAction="http://tempuri.org/IAccountServiceMvc/LoginAccountResponse")]
        AccountService.SerializableUser LoginAccount(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/LoginAccount", ReplyAction="http://tempuri.org/IAccountServiceMvc/LoginAccountResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableUser> LoginAccountAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddKitchen", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddKitchenResponse")]
        int AddKitchen(int userId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddKitchen", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddKitchenResponse")]
        System.Threading.Tasks.Task<int> AddKitchenAsync(int userId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetKitchens", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetKitchensResponse")]
        AccountService.SerializableKitchen[] GetKitchens(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetKitchens", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetKitchensResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableKitchen[]> GetKitchensAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetPrimaryInventory", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetPrimaryInventoryResponse")]
        AccountService.SerializableFood[] GetPrimaryInventory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetPrimaryInventory", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetPrimaryInventoryResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableFood[]> GetPrimaryInventoryAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetInventory", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetInventoryResponse")]
        AccountService.SerializableFood[] GetInventory(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetInventory", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetInventoryResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableFood[]> GetInventoryAsync(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetStorages", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetStoragesResponse")]
        AccountService.Storage[] GetStorages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetStorages", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetStoragesResponse")]
        System.Threading.Tasks.Task<AccountService.Storage[]> GetStoragesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetBarcodeData", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetBarcodeDataResponse")]
        string GetBarcodeData(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetBarcodeData", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetBarcodeDataResponse")]
        System.Threading.Tasks.Task<string> GetBarcodeDataAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetAllOpenFoodFacts", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetAllOpenFoodFactsResponse")]
        AccountService.SerializableFoodFactsProductModel GetAllOpenFoodFacts(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetAllOpenFoodFacts", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetAllOpenFoodFactsResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableFoodFactsProductModel> GetAllOpenFoodFactsAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddFoodResponse")]
        bool AddFood(int userId, int kitchenId, string name, int quantity, System.Nullable<System.DateTime> expiryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddFoodResponse")]
        System.Threading.Tasks.Task<bool> AddFoodAsync(int userId, int kitchenId, string name, int quantity, System.Nullable<System.DateTime> expiryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddFoodComplete", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddFoodCompleteResponse")]
        bool AddFoodComplete(int userId, int kitchenId, string name, string storage, System.Nullable<System.DateTime> expiryDate, double quantity, string quantityClassifier, int vegan, int vegetarian, string[] ingredients, string[] traces, bool favourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AddFoodComplete", ReplyAction="http://tempuri.org/IAccountServiceMvc/AddFoodCompleteResponse")]
        System.Threading.Tasks.Task<bool> AddFoodCompleteAsync(int userId, int kitchenId, string name, string storage, System.Nullable<System.DateTime> expiryDate, double quantity, string quantityClassifier, int vegan, int vegetarian, string[] ingredients, string[] traces, bool favourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EatFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/EatFoodResponse")]
        bool EatFood(int id, double quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EatFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/EatFoodResponse")]
        System.Threading.Tasks.Task<bool> EatFoodAsync(int id, double quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditFoodResponse")]
        bool EditFood(int id, string name, double quantity, string quantityClassifier, string storage, System.Nullable<System.DateTime> expiryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditFoodResponse")]
        System.Threading.Tasks.Task<bool> EditFoodAsync(int id, string name, double quantity, string quantityClassifier, string storage, System.Nullable<System.DateTime> expiryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FavouriteFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/FavouriteFoodResponse")]
        bool FavouriteFood(int foodId, bool favourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FavouriteFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/FavouriteFoodResponse")]
        System.Threading.Tasks.Task<bool> FavouriteFoodAsync(int foodId, bool favourite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ShoppingListFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/ShoppingListFoodResponse")]
        bool ShoppingListFood(int foodId, bool onShoppingList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ShoppingListFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/ShoppingListFoodResponse")]
        System.Threading.Tasks.Task<bool> ShoppingListFoodAsync(int foodId, bool onShoppingList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ClearShoppingList", ReplyAction="http://tempuri.org/IAccountServiceMvc/ClearShoppingListResponse")]
        bool ClearShoppingList(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ClearShoppingList", ReplyAction="http://tempuri.org/IAccountServiceMvc/ClearShoppingListResponse")]
        System.Threading.Tasks.Task<bool> ClearShoppingListAsync(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserDietaryRestrictions", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserDietaryRestrictionsResponse")]
        bool EditUserDietaryRestrictions(int id, bool vegan, bool vegetarian, string[] allergies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserDietaryRestrictions", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserDietaryRestrictionsResponse")]
        System.Threading.Tasks.Task<bool> EditUserDietaryRestrictionsAsync(int id, bool vegan, bool vegetarian, string[] allergies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserPassword", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserPasswordResponse")]
        bool EditUserPassword(int id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserPassword", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> EditUserPasswordAsync(int id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserEmail", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserEmailResponse")]
        bool EditUserEmail(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditUserEmail", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditUserEmailResponse")]
        System.Threading.Tasks.Task<bool> EditUserEmailAsync(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/RemoveItem", ReplyAction="http://tempuri.org/IAccountServiceMvc/RemoveItemResponse")]
        bool RemoveItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/RemoveItem", ReplyAction="http://tempuri.org/IAccountServiceMvc/RemoveItemResponse")]
        System.Threading.Tasks.Task<bool> RemoveItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GenerateShoppingList", ReplyAction="http://tempuri.org/IAccountServiceMvc/GenerateShoppingListResponse")]
        string[] GenerateShoppingList(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GenerateShoppingList", ReplyAction="http://tempuri.org/IAccountServiceMvc/GenerateShoppingListResponse")]
        System.Threading.Tasks.Task<string[]> GenerateShoppingListAsync(int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/Test", ReplyAction="http://tempuri.org/IAccountServiceMvc/TestResponse")]
        AccountService.SerializableUser[] Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/Test", ReplyAction="http://tempuri.org/IAccountServiceMvc/TestResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableUser[]> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetSerializableUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetSerializableUserResponse")]
        AccountService.SerializableUser GetSerializableUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetSerializableUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetSerializableUserResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableUser> GetSerializableUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetUserResponse")]
        AccountService.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetUserResponse")]
        System.Threading.Tasks.Task<AccountService.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetFoodResponse")]
        AccountService.Food GetFood(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/GetFood", ReplyAction="http://tempuri.org/IAccountServiceMvc/GetFoodResponse")]
        System.Threading.Tasks.Task<AccountService.Food> GetFoodAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipes", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesResponse")]
        AccountService.SerializableRecipeModel[] SearchRecipes(string search, int count, string[] diets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipes", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesAsync(string search, int count, string[] diets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipesUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesUserResponse")]
        AccountService.SerializableRecipeModel[] SearchRecipesUser(string search, int count, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipesUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesUserResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesUserAsync(string search, int count, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipesRanked", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesRankedResponse")]
        AccountService.SerializableRecipeModel[] SearchRecipesRanked(string search, int count, string[] diets, int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/SearchRecipesRanked", ReplyAction="http://tempuri.org/IAccountServiceMvc/SearchRecipesRankedResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesRankedAsync(string search, int count, string[] diets, int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FeelingLuckyUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/FeelingLuckyUserResponse")]
        AccountService.SerializableRecipeModel[] FeelingLuckyUser(int count, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FeelingLuckyUser", ReplyAction="http://tempuri.org/IAccountServiceMvc/FeelingLuckyUserResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> FeelingLuckyUserAsync(int count, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AnotherTest", ReplyAction="http://tempuri.org/IAccountServiceMvc/AnotherTestResponse")]
        bool AnotherTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/AnotherTest", ReplyAction="http://tempuri.org/IAccountServiceMvc/AnotherTestResponse")]
        System.Threading.Tasks.Task<bool> AnotherTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FeelingLucky", ReplyAction="http://tempuri.org/IAccountServiceMvc/FeelingLuckyResponse")]
        AccountService.SerializableRecipeModel[] FeelingLucky(int count, string[] diets, int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/FeelingLucky", ReplyAction="http://tempuri.org/IAccountServiceMvc/FeelingLuckyResponse")]
        System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> FeelingLuckyAsync(int count, string[] diets, int kitchenId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ConfirmEmail", ReplyAction="http://tempuri.org/IAccountServiceMvc/ConfirmEmailResponse")]
        string ConfirmEmail(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/ConfirmEmail", ReplyAction="http://tempuri.org/IAccountServiceMvc/ConfirmEmailResponse")]
        System.Threading.Tasks.Task<string> ConfirmEmailAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/DemoDb", ReplyAction="http://tempuri.org/IAccountServiceMvc/DemoDbResponse")]
        bool DemoDb(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/DemoDb", ReplyAction="http://tempuri.org/IAccountServiceMvc/DemoDbResponse")]
        System.Threading.Tasks.Task<bool> DemoDbAsync(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditShoppingListMultiple", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditShoppingListMultipleResponse")]
        bool EditShoppingListMultiple(int kId, AccountService.SerializableFood[] shoppingList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountServiceMvc/EditShoppingListMultiple", ReplyAction="http://tempuri.org/IAccountServiceMvc/EditShoppingListMultipleResponse")]
        System.Threading.Tasks.Task<bool> EditShoppingListMultipleAsync(int kId, AccountService.SerializableFood[] shoppingList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAccountServiceMvcChannel : AccountService.IAccountServiceMvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AccountServiceMvcClient : System.ServiceModel.ClientBase<AccountService.IAccountServiceMvc>, AccountService.IAccountServiceMvc
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountServiceMvcClient() : 
                base(AccountServiceMvcClient.GetDefaultBinding(), AccountServiceMvcClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAccountServiceMvc.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceMvcClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountServiceMvcClient.GetBindingForEndpoint(endpointConfiguration), AccountServiceMvcClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceMvcClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountServiceMvcClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceMvcClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountServiceMvcClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceMvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public AccountService.SerializableUser CreateAccount(string email, string pass)
        {
            return base.Channel.CreateAccount(email, pass);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableUser> CreateAccountAsync(string email, string pass)
        {
            return base.Channel.CreateAccountAsync(email, pass);
        }
        
        public AccountService.SerializableUser LoginAccount(string email, string pass)
        {
            return base.Channel.LoginAccount(email, pass);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableUser> LoginAccountAsync(string email, string pass)
        {
            return base.Channel.LoginAccountAsync(email, pass);
        }
        
        public int AddKitchen(int userId, string name)
        {
            return base.Channel.AddKitchen(userId, name);
        }
        
        public System.Threading.Tasks.Task<int> AddKitchenAsync(int userId, string name)
        {
            return base.Channel.AddKitchenAsync(userId, name);
        }
        
        public AccountService.SerializableKitchen[] GetKitchens(int userId)
        {
            return base.Channel.GetKitchens(userId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableKitchen[]> GetKitchensAsync(int userId)
        {
            return base.Channel.GetKitchensAsync(userId);
        }
        
        public AccountService.SerializableFood[] GetPrimaryInventory(int userId)
        {
            return base.Channel.GetPrimaryInventory(userId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableFood[]> GetPrimaryInventoryAsync(int userId)
        {
            return base.Channel.GetPrimaryInventoryAsync(userId);
        }
        
        public AccountService.SerializableFood[] GetInventory(int kitchenId)
        {
            return base.Channel.GetInventory(kitchenId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableFood[]> GetInventoryAsync(int kitchenId)
        {
            return base.Channel.GetInventoryAsync(kitchenId);
        }
        
        public AccountService.Storage[] GetStorages()
        {
            return base.Channel.GetStorages();
        }
        
        public System.Threading.Tasks.Task<AccountService.Storage[]> GetStoragesAsync()
        {
            return base.Channel.GetStoragesAsync();
        }
        
        public string GetBarcodeData(string barcode)
        {
            return base.Channel.GetBarcodeData(barcode);
        }
        
        public System.Threading.Tasks.Task<string> GetBarcodeDataAsync(string barcode)
        {
            return base.Channel.GetBarcodeDataAsync(barcode);
        }
        
        public AccountService.SerializableFoodFactsProductModel GetAllOpenFoodFacts(string barcode)
        {
            return base.Channel.GetAllOpenFoodFacts(barcode);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableFoodFactsProductModel> GetAllOpenFoodFactsAsync(string barcode)
        {
            return base.Channel.GetAllOpenFoodFactsAsync(barcode);
        }
        
        public bool AddFood(int userId, int kitchenId, string name, int quantity, System.Nullable<System.DateTime> expiryDate)
        {
            return base.Channel.AddFood(userId, kitchenId, name, quantity, expiryDate);
        }
        
        public System.Threading.Tasks.Task<bool> AddFoodAsync(int userId, int kitchenId, string name, int quantity, System.Nullable<System.DateTime> expiryDate)
        {
            return base.Channel.AddFoodAsync(userId, kitchenId, name, quantity, expiryDate);
        }
        
        public bool AddFoodComplete(int userId, int kitchenId, string name, string storage, System.Nullable<System.DateTime> expiryDate, double quantity, string quantityClassifier, int vegan, int vegetarian, string[] ingredients, string[] traces, bool favourite)
        {
            return base.Channel.AddFoodComplete(userId, kitchenId, name, storage, expiryDate, quantity, quantityClassifier, vegan, vegetarian, ingredients, traces, favourite);
        }
        
        public System.Threading.Tasks.Task<bool> AddFoodCompleteAsync(int userId, int kitchenId, string name, string storage, System.Nullable<System.DateTime> expiryDate, double quantity, string quantityClassifier, int vegan, int vegetarian, string[] ingredients, string[] traces, bool favourite)
        {
            return base.Channel.AddFoodCompleteAsync(userId, kitchenId, name, storage, expiryDate, quantity, quantityClassifier, vegan, vegetarian, ingredients, traces, favourite);
        }
        
        public bool EatFood(int id, double quantity)
        {
            return base.Channel.EatFood(id, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> EatFoodAsync(int id, double quantity)
        {
            return base.Channel.EatFoodAsync(id, quantity);
        }
        
        public bool EditFood(int id, string name, double quantity, string quantityClassifier, string storage, System.Nullable<System.DateTime> expiryDate)
        {
            return base.Channel.EditFood(id, name, quantity, quantityClassifier, storage, expiryDate);
        }
        
        public System.Threading.Tasks.Task<bool> EditFoodAsync(int id, string name, double quantity, string quantityClassifier, string storage, System.Nullable<System.DateTime> expiryDate)
        {
            return base.Channel.EditFoodAsync(id, name, quantity, quantityClassifier, storage, expiryDate);
        }
        
        public bool FavouriteFood(int foodId, bool favourite)
        {
            return base.Channel.FavouriteFood(foodId, favourite);
        }
        
        public System.Threading.Tasks.Task<bool> FavouriteFoodAsync(int foodId, bool favourite)
        {
            return base.Channel.FavouriteFoodAsync(foodId, favourite);
        }
        
        public bool ShoppingListFood(int foodId, bool onShoppingList)
        {
            return base.Channel.ShoppingListFood(foodId, onShoppingList);
        }
        
        public System.Threading.Tasks.Task<bool> ShoppingListFoodAsync(int foodId, bool onShoppingList)
        {
            return base.Channel.ShoppingListFoodAsync(foodId, onShoppingList);
        }
        
        public bool ClearShoppingList(int kitchenId)
        {
            return base.Channel.ClearShoppingList(kitchenId);
        }
        
        public System.Threading.Tasks.Task<bool> ClearShoppingListAsync(int kitchenId)
        {
            return base.Channel.ClearShoppingListAsync(kitchenId);
        }
        
        public bool EditUserDietaryRestrictions(int id, bool vegan, bool vegetarian, string[] allergies)
        {
            return base.Channel.EditUserDietaryRestrictions(id, vegan, vegetarian, allergies);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserDietaryRestrictionsAsync(int id, bool vegan, bool vegetarian, string[] allergies)
        {
            return base.Channel.EditUserDietaryRestrictionsAsync(id, vegan, vegetarian, allergies);
        }
        
        public bool EditUserPassword(int id, string password)
        {
            return base.Channel.EditUserPassword(id, password);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserPasswordAsync(int id, string password)
        {
            return base.Channel.EditUserPasswordAsync(id, password);
        }
        
        public bool EditUserEmail(int id, string email)
        {
            return base.Channel.EditUserEmail(id, email);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserEmailAsync(int id, string email)
        {
            return base.Channel.EditUserEmailAsync(id, email);
        }
        
        public bool RemoveItem(int id)
        {
            return base.Channel.RemoveItem(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveItemAsync(int id)
        {
            return base.Channel.RemoveItemAsync(id);
        }
        
        public string[] GenerateShoppingList(int kitchenId)
        {
            return base.Channel.GenerateShoppingList(kitchenId);
        }
        
        public System.Threading.Tasks.Task<string[]> GenerateShoppingListAsync(int kitchenId)
        {
            return base.Channel.GenerateShoppingListAsync(kitchenId);
        }
        
        public AccountService.SerializableUser[] Test()
        {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableUser[]> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public AccountService.SerializableUser GetSerializableUser(int id)
        {
            return base.Channel.GetSerializableUser(id);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableUser> GetSerializableUserAsync(int id)
        {
            return base.Channel.GetSerializableUserAsync(id);
        }
        
        public AccountService.User GetUser(int id)
        {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<AccountService.User> GetUserAsync(int id)
        {
            return base.Channel.GetUserAsync(id);
        }
        
        public AccountService.Food GetFood(int id)
        {
            return base.Channel.GetFood(id);
        }
        
        public System.Threading.Tasks.Task<AccountService.Food> GetFoodAsync(int id)
        {
            return base.Channel.GetFoodAsync(id);
        }
        
        public AccountService.SerializableRecipeModel[] SearchRecipes(string search, int count, string[] diets)
        {
            return base.Channel.SearchRecipes(search, count, diets);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesAsync(string search, int count, string[] diets)
        {
            return base.Channel.SearchRecipesAsync(search, count, diets);
        }
        
        public AccountService.SerializableRecipeModel[] SearchRecipesUser(string search, int count, int userId)
        {
            return base.Channel.SearchRecipesUser(search, count, userId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesUserAsync(string search, int count, int userId)
        {
            return base.Channel.SearchRecipesUserAsync(search, count, userId);
        }
        
        public AccountService.SerializableRecipeModel[] SearchRecipesRanked(string search, int count, string[] diets, int kitchenId)
        {
            return base.Channel.SearchRecipesRanked(search, count, diets, kitchenId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> SearchRecipesRankedAsync(string search, int count, string[] diets, int kitchenId)
        {
            return base.Channel.SearchRecipesRankedAsync(search, count, diets, kitchenId);
        }
        
        public AccountService.SerializableRecipeModel[] FeelingLuckyUser(int count, int userId)
        {
            return base.Channel.FeelingLuckyUser(count, userId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> FeelingLuckyUserAsync(int count, int userId)
        {
            return base.Channel.FeelingLuckyUserAsync(count, userId);
        }
        
        public bool AnotherTest()
        {
            return base.Channel.AnotherTest();
        }
        
        public System.Threading.Tasks.Task<bool> AnotherTestAsync()
        {
            return base.Channel.AnotherTestAsync();
        }
        
        public AccountService.SerializableRecipeModel[] FeelingLucky(int count, string[] diets, int kitchenId)
        {
            return base.Channel.FeelingLucky(count, diets, kitchenId);
        }
        
        public System.Threading.Tasks.Task<AccountService.SerializableRecipeModel[]> FeelingLuckyAsync(int count, string[] diets, int kitchenId)
        {
            return base.Channel.FeelingLuckyAsync(count, diets, kitchenId);
        }
        
        public string ConfirmEmail(string key)
        {
            return base.Channel.ConfirmEmail(key);
        }
        
        public System.Threading.Tasks.Task<string> ConfirmEmailAsync(string key)
        {
            return base.Channel.ConfirmEmailAsync(key);
        }
        
        public bool DemoDb(string pass)
        {
            return base.Channel.DemoDb(pass);
        }
        
        public System.Threading.Tasks.Task<bool> DemoDbAsync(string pass)
        {
            return base.Channel.DemoDbAsync(pass);
        }
        
        public bool EditShoppingListMultiple(int kId, AccountService.SerializableFood[] shoppingList)
        {
            return base.Channel.EditShoppingListMultiple(kId, shoppingList);
        }
        
        public System.Threading.Tasks.Task<bool> EditShoppingListMultipleAsync(int kId, AccountService.SerializableFood[] shoppingList)
        {
            return base.Channel.EditShoppingListMultipleAsync(kId, shoppingList);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountServiceMvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountServiceMvc))
            {
                return new System.ServiceModel.EndpointAddress("http://142.55.32.86:50241/AccountServiceMvc.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AccountServiceMvcClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAccountServiceMvc);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AccountServiceMvcClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAccountServiceMvc);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAccountServiceMvc,
        }
    }
}
